import { School, StudentProfile, CounselingSession, Notification, AIRecommendation } from '../types';

// Mock Schools Data
export const mockSchools: School[] = [
  {
    id: '1',
    name: 'Trường THPT Nguyễn Thượng Hiền',
    logo: 'https://via.placeholder.com/100',
    address: '456 Nguyễn Thượng Hiền, Phường 5',
    ward: 'Phường 5',
    district: 'Quận 3',
    description: 'Trường THPT chất lượng cao với đội ngũ giáo viên giàu kinh nghiệm, cơ sở vật chất hiện đại.',
    programs: ['Chương trình Tiêu chuẩn', 'Chương trình Tích hợp', 'Chương trình Song ngữ'],
    tuition: {
      min: 15000000,
      max: 25000000,
    },
    cutoffScores: [
      { year: 2023, score: 28.5 },
      { year: 2024, score: 29.0 },
      { year: 2025, score: 29.5 },
    ],
    images: [
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
    ],
    rating: 4.5,
    phone: '028 3932 4567',
    email: 'info@nthuonghien.edu.vn',
    website: 'https://nthuonghien.edu.vn',
  },
  {
    id: '2',
    name: 'Trường THPT Lê Quý Đôn',
    logo: 'https://via.placeholder.com/100',
    address: '123 Lê Quý Đôn, Phường 7',
    ward: 'Phường 7',
    district: 'Quận 3',
    description: 'Ngôi trường với truyền thống lâu đời, môi trường học tập chuyên nghiệp và thân thiện.',
    programs: ['Chương trình Tiêu chuẩn', 'Chương trình Nâng cao'],
    tuition: {
      min: 12000000,
      max: 20000000,
    },
    cutoffScores: [
      { year: 2023, score: 27.0 },
      { year: 2024, score: 27.5 },
      { year: 2025, score: 28.0 },
    ],
    images: [
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
    ],
    rating: 4.3,
    phone: '028 3933 5678',
    email: 'contact@lequydon.edu.vn',
    website: 'https://lequydon.edu.vn',
  },
  {
    id: '3',
    name: 'Trường THPT Võ Trường Toản',
    logo: 'https://via.placeholder.com/100',
    address: '789 Võ Trường Toản, Phường 12',
    ward: 'Phường 12',
    district: 'Quận 10',
    description: 'Trường học hiện đại với phương pháp giảng dạy tiên tiến, tập trung phát triển năng lực học sinh.',
    programs: ['Chương trình Tiêu chuẩn', 'Chương trình Tích hợp', 'Chương trình Quốc tế'],
    tuition: {
      min: 18000000,
      max: 30000000,
    },
    cutoffScores: [
      { year: 2023, score: 29.0 },
      { year: 2024, score: 29.5 },
      { year: 2025, score: 30.0 },
    ],
    images: [
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
    ],
    rating: 4.7,
    phone: '028 3865 1234',
    email: 'info@votruongtoan.edu.vn',
    website: 'https://votruongtoan.edu.vn',
  },
  {
    id: '4',
    name: 'Trường THPT Hùng Vương',
    logo: 'https://via.placeholder.com/100',
    address: '234 Hùng Vương, Phường 1',
    ward: 'Phường 1',
    district: 'Quận 5',
    description: 'Trường có bề dày thành tích học tập và hoạt động ngoại khóa phong phú.',
    programs: ['Chương trình Tiêu chuẩn', 'Chương trình Song ngữ'],
    tuition: {
      min: 14000000,
      max: 22000000,
    },
    cutoffScores: [
      { year: 2023, score: 26.5 },
      { year: 2024, score: 27.0 },
      { year: 2025, score: 27.5 },
    ],
    images: [
      'https://via.placeholder.com/400x300',
    ],
    rating: 4.4,
    phone: '028 3855 6789',
    email: 'contact@hungvuong.edu.vn',
    website: 'https://hungvuong.edu.vn',
  },
  {
    id: '5',
    name: 'Trường THPT Trần Đại Nghĩa',
    logo: 'https://via.placeholder.com/100',
    address: '567 Trần Đại Nghĩa, Phường 10',
    ward: 'Phường 10',
    district: 'Quận 1',
    description: 'Ngôi trường danh tiếng với chất lượng giáo dục xuất sắc và cơ sở vật chất hàng đầu.',
    programs: ['Chương trình Tiêu chuẩn', 'Chương trình Nâng cao', 'Chương trình Tích hợp'],
    tuition: {
      min: 20000000,
      max: 35000000,
    },
    cutoffScores: [
      { year: 2023, score: 30.0 },
      { year: 2024, score: 30.5 },
      { year: 2025, score: 31.0 },
    ],
    images: [
      'https://via.placeholder.com/400x300',
      'https://via.placeholder.com/400x300',
    ],
    rating: 4.9,
    phone: '028 3822 3456',
    email: 'info@trandainghia.edu.vn',
    website: 'https://trandainghia.edu.vn',
  },
];

// Mock Student Profile
export const mockStudentProfile: StudentProfile = {
  id: 'student1',
  name: 'Nguyễn Văn An',
  email: 'nguyenvanan@gmail.com',
  avatar: 'https://via.placeholder.com/150',
  grade: 9,
  mathScore: 8.5,
  literatureScore: 8.0,
  englishScore: 9.0,
  preferredDistricts: ['Quận 1', 'Quận 3', 'Quận 10'],
  tuitionBudget: 25000000,
  savedSchools: ['1', '3', '5'],
};

// Mock Counseling Sessions
export const mockCounselingSessions: CounselingSession[] = [
  {
    id: 'session1',
    counselorId: 'counselor1',
    counselorName: 'Thầy Trần Văn B',
    counselorAvatar: 'https://via.placeholder.com/100',
    schoolId: '1',
    schoolName: 'Trường THPT Nguyễn Thượng Hiền',
    status: 'in-progress',
    scheduledDate: '2026-01-25T10:00:00',
    messages: [
      {
        id: 'msg1',
        senderId: 'counselor1',
        senderName: 'Thầy Trần Văn B',
        content: 'Xin chào! Tôi là tư vấn viên của trường THPT Nguyễn Thượng Hiền. Em có câu hỏi gì không?',
        timestamp: '2026-01-20T09:00:00',
        isOwn: false,
      },
      {
        id: 'msg2',
        senderId: 'student1',
        senderName: 'Nguyễn Văn An',
        content: 'Thưa thầy, em muốn hỏi về chương trình học và học phí ạ.',
        timestamp: '2026-01-20T09:05:00',
        isOwn: true,
      },
    ],
  },
  {
    id: 'session2',
    counselorId: 'counselor2',
    counselorName: 'Cô Lê Thị C',
    counselorAvatar: 'https://via.placeholder.com/100',
    schoolId: '3',
    schoolName: 'Trường THPT Võ Trường Toản',
    status: 'completed',
    scheduledDate: '2026-01-18T14:00:00',
    messages: [],
    rating: 5,
    feedback: 'Cô tư vấn rất nhiệt tình và chi tiết!',
  },
  {
    id: 'session3',
    counselorId: 'counselor3',
    counselorName: 'Thầy Phạm Văn D',
    counselorAvatar: 'https://via.placeholder.com/100',
    schoolId: '5',
    schoolName: 'Trường THPT Trần Đại Nghĩa',
    status: 'pending',
    scheduledDate: '2026-01-28T15:00:00',
    messages: [],
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif1',
    title: 'Cập nhật điểm chuẩn',
    message: 'Trường THPT Nguyễn Thượng Hiền vừa công bố điểm chuẩn dự kiến năm 2026',
    type: 'cutoff',
    timestamp: '2026-01-20T08:00:00',
    read: false,
    schoolId: '1',
  },
  {
    id: 'notif2',
    title: 'Nhắc nhở deadline',
    message: 'Còn 30 ngày đến hạn nộp hồ sơ xét tuyển vào các trường THPT',
    type: 'deadline',
    timestamp: '2026-01-19T10:00:00',
    read: true,
  },
  {
    id: 'notif3',
    title: 'Lịch tư vấn sắp tới',
    message: 'Bạn có buổi tư vấn với Thầy Trần Văn B vào ngày 25/01/2026',
    type: 'counseling',
    timestamp: '2026-01-19T15:30:00',
    read: false,
  },
  {
    id: 'notif4',
    title: 'Mẹo ôn thi',
    message: 'Khám phá 5 phương pháp ôn thi hiệu quả cho kỳ thi tuyển sinh lớp 10',
    type: 'general',
    timestamp: '2026-01-18T09:00:00',
    read: true,
  },
];

// Mock AI Recommendations
export const mockAIRecommendations: AIRecommendation[] = [
  {
    schoolId: '5',
    schoolName: 'Trường THPT Trần Đại Nghĩa',
    logo: 'https://via.placeholder.com/100',
    probability: 85,
    reasons: [
      'Điểm số của em phù hợp với điểm chuẩn',
      'Nằm trong khu vực em mong muốn',
      'Học phí phù hợp với ngân sách',
    ],
    matchScore: 95,
    district: 'Quận 1',
    tuition: 27500000,
  },
  {
    schoolId: '1',
    schoolName: 'Trường THPT Nguyễn Thượng Hiền',
    logo: 'https://via.placeholder.com/100',
    probability: 90,
    reasons: [
      'Điểm số cao hơn điểm chuẩn',
      'Chương trình học phù hợp với năng lực',
      'Có chương trình song ngữ mạnh',
    ],
    matchScore: 92,
    district: 'Quận 3',
    tuition: 20000000,
  },
  {
    schoolId: '3',
    schoolName: 'Trường THPT Võ Trường Toản',
    logo: 'https://via.placeholder.com/100',
    probability: 88,
    reasons: [
      'Chương trình tích hợp phù hợp',
      'Cơ sở vật chất hiện đại',
      'Điểm chuẩn trong tầm',
    ],
    matchScore: 90,
    district: 'Quận 10',
    tuition: 24000000,
  },
  {
    schoolId: '2',
    schoolName: 'Trường THPT Lê Quý Đôn',
    logo: 'https://via.placeholder.com/100',
    probability: 92,
    reasons: [
      'Điểm số vượt điểm chuẩn',
      'Học phí hợp lý',
      'Truyền thống giáo dục tốt',
    ],
    matchScore: 88,
    district: 'Quận 3',
    tuition: 16000000,
  },
  {
    schoolId: '4',
    schoolName: 'Trường THPT Hùng Vương',
    logo: 'https://via.placeholder.com/100',
    probability: 94,
    reasons: [
      'Điểm chuẩn phù hợp',
      'Hoạt động ngoại khóa phong phú',
      'Học phí trong tầm',
    ],
    matchScore: 85,
    district: 'Quận 5',
    tuition: 18000000,
  },
];

// Districts in HCMC
export const districts = [
  'Quận 1',
  'Quận 2',
  'Quận 3',
  'Quận 4',
  'Quận 5',
  'Quận 6',
  'Quận 7',
  'Quận 8',
  'Quận 9',
  'Quận 10',
  'Quận 11',
  'Quận 12',
  'Quận Bình Thạnh',
  'Quận Tân Bình',
  'Quận Phú Nhuận',
  'Quận Gò Vấp',
];
